/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GoldRouteImport } from './routes/gold'
import { Route as PearlRouteImport } from './routes/pearl'
import { Route as SilverRouteImport } from './routes/silver'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminPromotionRouteImport } from './routes/admin/promotion'
import { Route as AdminPurchaseRouteImport } from './routes/admin/purchase'
import { Route as AdminStockRouteImport } from './routes/admin/stock'
import { Route as AdminBillingIndexRouteImport } from './routes/admin/billing/index'
import { Route as AdminBillingIdRouteImport } from './routes/admin/billing/$id'
import { Route as AdminBillingNewRouteImport } from './routes/admin/billing/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldRoute = GoldRouteImport.update({
  id: '/gold',
  path: '/gold',
  getParentRoute: () => rootRouteImport,
} as any)
const PearlRoute = PearlRouteImport.update({
  id: '/pearl',
  path: '/pearl',
  getParentRoute: () => rootRouteImport,
} as any)
const SilverRoute = SilverRouteImport.update({
  id: '/silver',
  path: '/silver',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPromotionRoute = AdminPromotionRouteImport.update({
  id: '/promotion',
  path: '/promotion',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPurchaseRoute = AdminPurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStockRoute = AdminStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBillingIndexRoute = AdminBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBillingIdRoute = AdminBillingIdRouteImport.update({
  id: '/billing/$id',
  path: '/billing/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBillingNewRoute = AdminBillingNewRouteImport.update({
  id: '/billing/new',
  path: '/billing/new',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gold': typeof GoldRoute
  '/pearl': typeof PearlRoute
  '/silver': typeof SilverRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/promotion': typeof AdminPromotionRoute
  '/admin/purchase': typeof AdminPurchaseRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/billing/$id': typeof AdminBillingIdRoute
  '/admin/billing/new': typeof AdminBillingNewRoute
  '/admin/billing/': typeof AdminBillingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gold': typeof GoldRoute
  '/pearl': typeof PearlRoute
  '/silver': typeof SilverRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/promotion': typeof AdminPromotionRoute
  '/admin/purchase': typeof AdminPurchaseRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin': typeof AdminIndexRoute
  '/admin/billing/$id': typeof AdminBillingIdRoute
  '/admin/billing/new': typeof AdminBillingNewRoute
  '/admin/billing': typeof AdminBillingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gold': typeof GoldRoute
  '/pearl': typeof PearlRoute
  '/silver': typeof SilverRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/promotion': typeof AdminPromotionRoute
  '/admin/purchase': typeof AdminPurchaseRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/billing/$id': typeof AdminBillingIdRoute
  '/admin/billing/new': typeof AdminBillingNewRoute
  '/admin/billing/': typeof AdminBillingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/contact'
    | '/gold'
    | '/pearl'
    | '/silver'
    | '/admin/login'
    | '/admin/promotion'
    | '/admin/purchase'
    | '/admin/stock'
    | '/admin/'
    | '/admin/billing/$id'
    | '/admin/billing/new'
    | '/admin/billing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gold'
    | '/pearl'
    | '/silver'
    | '/admin/login'
    | '/admin/promotion'
    | '/admin/purchase'
    | '/admin/stock'
    | '/admin'
    | '/admin/billing/$id'
    | '/admin/billing/new'
    | '/admin/billing'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/contact'
    | '/gold'
    | '/pearl'
    | '/silver'
    | '/admin/login'
    | '/admin/promotion'
    | '/admin/purchase'
    | '/admin/stock'
    | '/admin/'
    | '/admin/billing/$id'
    | '/admin/billing/new'
    | '/admin/billing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GoldRoute: typeof GoldRoute
  PearlRoute: typeof PearlRoute
  SilverRoute: typeof SilverRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold': {
      id: '/gold'
      path: '/gold'
      fullPath: '/gold'
      preLoaderRoute: typeof GoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pearl': {
      id: '/pearl'
      path: '/pearl'
      fullPath: '/pearl'
      preLoaderRoute: typeof PearlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/silver': {
      id: '/silver'
      path: '/silver'
      fullPath: '/silver'
      preLoaderRoute: typeof SilverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/promotion': {
      id: '/admin/promotion'
      path: '/promotion'
      fullPath: '/admin/promotion'
      preLoaderRoute: typeof AdminPromotionRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/purchase': {
      id: '/admin/purchase'
      path: '/purchase'
      fullPath: '/admin/purchase'
      preLoaderRoute: typeof AdminPurchaseRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/stock': {
      id: '/admin/stock'
      path: '/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AdminStockRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/billing/': {
      id: '/admin/billing/'
      path: '/billing'
      fullPath: '/admin/billing/'
      preLoaderRoute: typeof AdminBillingIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/billing/$id': {
      id: '/admin/billing/$id'
      path: '/billing/$id'
      fullPath: '/admin/billing/$id'
      preLoaderRoute: typeof AdminBillingIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/billing/new': {
      id: '/admin/billing/new'
      path: '/billing/new'
      fullPath: '/admin/billing/new'
      preLoaderRoute: typeof AdminBillingNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPromotionRoute: typeof AdminPromotionRoute
  AdminPurchaseRoute: typeof AdminPurchaseRoute
  AdminStockRoute: typeof AdminStockRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBillingIdRoute: typeof AdminBillingIdRoute
  AdminBillingNewRoute: typeof AdminBillingNewRoute
  AdminBillingIndexRoute: typeof AdminBillingIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminPromotionRoute: AdminPromotionRoute,
  AdminPurchaseRoute: AdminPurchaseRoute,
  AdminStockRoute: AdminStockRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBillingIdRoute: AdminBillingIdRoute,
  AdminBillingNewRoute: AdminBillingNewRoute,
  AdminBillingIndexRoute: AdminBillingIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GoldRoute: GoldRoute,
  PearlRoute: PearlRoute,
  SilverRoute: SilverRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
